#@TYPE: Machine
#@NAME: Ultimate Truck Hacking Platform
#@DESCRIPTION: Custom configuration for UTHP based on BeagleBone

# Inherit settings from beaglebone.conf in meta-ti layer
require conf/machine/beaglebone.conf
# File naming convention for Yocto is image-machine.wks
# TODO: validate kernel-module-lin

# plc4trucksduck pru code only works on 6.6 and only on meta-ti 11.00.14 or earlier
TI_PREFERRED_BSP = "bb_org-6_6"
# PREFERRED_VERSION_linux-ti-staging="6.6.32" is what we want, but we need to use:
BSP_KERNEL_VERSION = "6.6.32"
