#@TYPE: Distribution
#@NAME: UTHP Custom Distro
#@DESCRIPTION: Custom distribution for UTHP based on Poky
DISTRO = "TruckHackingOS"
DISTRO_NAME = "TruckHackingOS"
DISTRO_VERSION = "1.0.5"
DISTRO_CODENAME = "Poky Scarthgap 5.0.8"
DISTRO_ID = "TruckHackingOS"
