#@TYPE: Distribution
#@NAME: Truck Hacking Custom Distro
#@DESCRIPTION: Custom distribution for TCAT based on Poky
DISTRO = "TruckHackingOS"
DISTRO_NAME = "TruckHackingOS"
DISTRO_VERSION = "1.0.6rc0"
DISTRO_CODENAME = "Poky Scarthgap 5.0.8"
DISTRO_ID = "TruckHackingOS"
DISTRO_FEATURES:append = " systemd systemd-resolved"
DISTRO_FEATURES:remove = "x11"
# Ensure nss-resolve is enabled in systemd PACKAGECONFIG
PACKAGECONFIG:append:pn-systemd = " resolved nss-resolve"
# try to reduce the system dependence on rust
PACKAGECONFIG:remove:pn-graphviz = "librsvg"
PACKAGECONFIG:remove:pn-systemd = "userdb"

# Explicitly request Python 3.11
PREFERRED_VERSION_python3 = "3.11%"
PYTHON_BASEVERSION = "3.11"
PACKAGECONFIG:append:pn-python3 = " readline"
PACKAGECONFIG:remove:pn-python3 = "editline"
PACKAGECONFIG:append:pn-python3-native = " readline"
PACKAGECONFIG:remove:pn-python3-native = "editline"
